version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/java:8-jdk

    steps:
      - checkout

      # - restore_cache:
      #     key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: ant

      # - save_cache:
      #     paths:
      #       - ~/.m2
      #     key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
